### ISSUE TITLE
链接跳转

### ISSUE THREAD

**Issue by lhy1024** [longfangsong/tipedia#51]
![image](https://user-images.githubusercontent.com/19542290/111310436-0b706b80-8698-11eb-8961-33fc29b68586.png)
![image](https://user-images.githubusercontent.com/19542290/111310442-0dd2c580-8698-11eb-8708-eab7e4f3ebe8.png)

这两个链接跳转不正确

**Comment by longfangsong** [comment]
Fixed in cd19928
